-- OPSIONAL: import satu kali item rutin dari Excel.
-- Jalankan setelah schema.sql + seed.sql / migrate_subcategories.sql.
-- Memakai sub-kategori (leaf) sebagai category_id.

insert into transactions (type, category_id, amount, description, owner, occurred_on, is_recurring)
values
  ('income',
    (select id from categories where name = 'Gaji Bulanan' and parent_id = (select id from categories where name = 'Gaji Pokok' and parent_id is null)),
    17000000, 'Gaji bulanan kantor - Ndod', 'suami', date_trunc('month', current_date)::date, true),

  ('expense',
    (select id from categories where name = 'Belanja Rumah Tangga' and parent_id = (select id from categories where name = 'Kebutuhan Pokok' and parent_id is null)),
    4500000, 'Kebutuhan pokok rumah tangga', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'KPR' and parent_id = (select id from categories where name = 'Tempat Tinggal' and parent_id is null)),
    3000000, 'KPR Northbend C1', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Filter Air Coway' and parent_id = (select id from categories where name = 'Cicilan / Utang' and parent_id is null)),
    300000, 'Filter air torrent Coway', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'HP' and parent_id = (select id from categories where name = 'Cicilan / Utang' and parent_id is null)),
    1434000, 'HP baru Devi', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Bensin & E-money' and parent_id = (select id from categories where name = 'Transportasi' and parent_id is null)),
    1750000, 'Bensin Mobil + E-money', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Service Mobil' and parent_id = (select id from categories where name = 'Transportasi' and parent_id is null)),
    150000, 'Service Mobil (proporsional per bulan)', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Pajak Mobil' and parent_id = (select id from categories where name = 'Transportasi' and parent_id is null)),
    125000, 'Pajak Mobil (proporsional per bulan)', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Asuransi' and parent_id = (select id from categories where name = 'Kesehatan' and parent_id is null)),
    750000, 'Asuransi Kesehatan Hendro', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Netflix' and parent_id = (select id from categories where name = 'Hiburan & Gaya Hidup' and parent_id is null)),
    46500, 'Netflix', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Dota+' and parent_id = (select id from categories where name = 'Hiburan & Gaya Hidup' and parent_id is null)),
    69000, 'Dota+', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Google Drive' and parent_id = (select id from categories where name = 'Hiburan & Gaya Hidup' and parent_id is null)),
    30000, 'Google Drive', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Jajan' and parent_id = (select id from categories where name = 'Hiburan & Gaya Hidup' and parent_id is null)),
    300000, 'Jajan Hendro', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Mama Hendro' and parent_id = (select id from categories where name = 'Dana Paramita' and parent_id is null)),
    500000, 'Bulanan Mama Hendro', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Shelter Doggy' and parent_id = (select id from categories where name = 'Dana Paramita' and parent_id is null)),
    70000, 'Shelter Doggy', 'suami', date_trunc('month', current_date)::date, true),
  ('expense',
    (select id from categories where name = 'Research Saham' and parent_id = (select id from categories where name = 'Skill Development' and parent_id is null)),
    750000, 'Research Saham', 'suami', date_trunc('month', current_date)::date, true);
